language: scala

scala:
  - "2.11.12"
jdk:
  - oraclejdk9
before_install:
  - pip install --quiet --user codecov
script:
  - sbt ++2.11.12 clean coverage test coverageReport
after_success:
  - codecov
